import 'package:flutter/material.dart';
import '../../../shared/widgets/onboarding_overlay.dart';

/// A small practice puzzle, independent of the scored round. Each entry names
/// the rule used by its game and explains a concrete example in both languages.
class GameCoaching {
  final String board;
  final int answer;
  final List<int> choices;
  final String questionEn, questionDe;
  final String focusEn, focusDe;
  final String strategyEn, strategyDe;
  final String workingEn, workingDe;
  const GameCoaching(
      this.board,
      this.answer,
      this.choices,
      this.questionEn,
      this.questionDe,
      this.focusEn,
      this.focusDe,
      this.strategyEn,
      this.strategyDe,
      this.workingEn,
      this.workingDe);
  OnboardingStep practice(bool german) => OnboardingStep(
      icon: Icons.school_outlined,
      practiceBoard: german ? (_germanPracticeBoards[board] ?? board) : board,
      choices: choices,
      answer: answer,
      body: german ? questionDe : questionEn,
      explanation: german ? workingDe : workingEn);
}

const gameCoaching = <String, GameCoaching>{
  "star_forge": GameCoaching(
      "8 + ? + 1 + 9 = 22",
      4,
      [3, 4, 5],
      "Fill the missing star node.",
      "Fülle den fehlenden Sternknoten.",
      "Look at an arm with one empty node.",
      "Suche einen Arm mit nur einer Lücke.",
      "Subtract the known nodes from its target; check overlapping arms.",
      "Ziehe die bekannten Zahlen vom Ziel ab und prüfe die überlappenden Arme.",
      "Example: 22 − 8 − 1 − 9 = 4. The shared node must also fit its other arm.",
      "Beispiel: 22 − 8 − 1 − 9 = 4. Der gemeinsame Knoten muss auch zum anderen Arm passen."),
  "number_walls": GameCoaching(
      "3 + 4 = ?",
      7,
      [6, 7, 8],
      "Build the brick above these two bricks.",
      "Baue den Stein über diesen beiden Steinen.",
      "Find three connected bricks with only one blank.",
      "Suche drei verbundene Steine mit nur einer Lücke.",
      "Use the operation shown. For addition, work upward by adding or downward by subtracting.",
      "Nutze das angezeigte Rechenzeichen. Bei Plus addierst du nach oben und subtrahierst nach unten.",
      "Example: 3 + 4 gives the top brick 7; with top 7 and lower 3, the other lower brick is 4.",
      "Beispiel: 3 + 4 ergibt oben 7. Bei oben 7 und unten 3 ist der andere untere Stein 4."),
  "orbital_towers": GameCoaching(
      "? → 2 → 1",
      3,
      [1, 2, 3],
      "The camera sees only one tower. Which height belongs first?",
      "Die Kamera sieht nur einen Turm. Welche Höhe gehört nach vorne?",
      "Start with a camera showing 1 or the full row length.",
      "Beginne mit einer Kamera, die 1 oder die volle Reihenlänge zeigt.",
      "A taller tower hides every shorter tower behind it. Also avoid repeats in each row and column.",
      "Ein höherer Turm verdeckt kleinere dahinter. Jede Höhe darf pro Zeile und Spalte nur einmal vorkommen.",
      "Example: 3, 2, 1 shows one tower from the left, but three from the right.",
      "Beispiel: 3, 2, 1 zeigt von links einen Turm und von rechts drei."),
  "magic_triangles": GameCoaching(
      "2 + ? + 4 = 9",
      3,
      [2, 3, 5],
      "Complete this triangle side.",
      "Vervollständige diese Dreiecksseite.",
      "Choose a side with the fewest empty nodes.",
      "Wähle die Seite mit den wenigsten Lücken.",
      "Subtract known values from the common side total; corners belong to two sides.",
      "Ziehe bekannte Werte von der Seitensumme ab. Ecken gehören zu zwei Seiten.",
      "Example: 9 − 2 − 4 = 3. Check the adjoining side before placing a corner.",
      "Beispiel: 9 − 2 − 4 = 3. Prüfe bei einer Ecke auch die angrenzende Seite."),
  "arithmatic_square": GameCoaching(
      "3 + ? = 8",
      5,
      [4, 5, 6],
      "Complete the equation.",
      "Vervollständige die Gleichung.",
      "Find an equation with one missing number.",
      "Suche eine Gleichung mit nur einer fehlenden Zahl.",
      "Use the inverse operation, then check the crossing equation and the remaining tray.",
      "Nutze die Umkehroperation. Prüfe dann die kreuzende Gleichung und die übrigen Zahlen.",
      "Example: 8 − 3 = 5, so the blank is 5. A crossing equation must accept the same value.",
      "Beispiel: 8 − 3 = 5, also gehört 5 in die Lücke. Die kreuzende Gleichung muss ebenfalls passen."),
  "arithmancer_crosswords": GameCoaching(
      "3 + ? = 8",
      5,
      [4, 5, 6],
      "Complete the equation.",
      "Vervollständige die Gleichung.",
      "Find an equation with one missing number.",
      "Suche eine Gleichung mit nur einer fehlenden Zahl.",
      "Use the inverse operation, then check the crossing equation and the remaining tray.",
      "Nutze die Umkehroperation. Prüfe dann die kreuzende Gleichung und die übrigen Zahlen.",
      "Example: 8 − 3 = 5, so the blank is 5. A crossing equation must accept the same value.",
      "Beispiel: 8 − 3 = 5, also gehört 5 in die Lücke. Die kreuzende Gleichung muss ebenfalls passen."),
  "solarpanel_game": GameCoaching(
      "A = 2, B = 3; A × B = ?",
      6,
      [5, 6, 9],
      "Find the power of the left panel.",
      "Berechne die Leistung des linken Panels.",
      "Look at the base numbers feeding a panel.",
      "Schau auf die Grundzahlen eines Panels.",
      "Multiply adjacent base numbers for each panel; add the two panel powers for the top.",
      "Multipliziere benachbarte Grundzahlen pro Panel. Addiere die beiden Panelleistungen für die Spitze.",
      "Example: bases 2, 3, 4 give panel powers 6 and 12, and total power 18.",
      "Beispiel: Die Grundzahlen 2, 3, 4 ergeben Panelleistungen 6 und 12 und insgesamt 18."),
  "asteroid_math": GameCoaching(
      "3 + 4 = ?",
      7,
      [6, 7, 8],
      "Solve the next target before tapping it.",
      "Löse das nächste Ziel, bevor du es antippst.",
      "Read the next target, rather than the nearest object.",
      "Lies das nächste Ziel, statt das nächste Objekt zu wählen.",
      "Calculate the expression first; then find that answer in the required order.",
      "Berechne zuerst den Ausdruck und suche dann diese Antwort in der geforderten Reihenfolge.",
      "Example: for target 7, the object labelled 3 + 4 is the match.",
      "Beispiel: Beim Ziel 7 passt das Objekt mit 3 + 4."),
  "bubble_math": GameCoaching(
      "3 + 4 = ?",
      7,
      [6, 7, 8],
      "Solve the next target before tapping it.",
      "Löse das nächste Ziel, bevor du es antippst.",
      "Read the next target, rather than the nearest object.",
      "Lies das nächste Ziel, statt das nächste Objekt zu wählen.",
      "Calculate the expression first; then find that answer in the required order.",
      "Berechne zuerst den Ausdruck und suche dann diese Antwort in der geforderten Reihenfolge.",
      "Example: for target 7, the object labelled 3 + 4 is the match.",
      "Beispiel: Beim Ziel 7 passt das Objekt mit 3 + 4."),
  "hyperdrive_gates": GameCoaching(
      "8 − 3 = ?",
      5,
      [4, 5, 6],
      "Choose the route with the correct answer.",
      "Wähle den Weg mit der richtigen Antwort.",
      "Read the current expression before choosing a route.",
      "Lies den aktuellen Ausdruck, bevor du einen Weg wählst.",
      "Break the calculation into small steps, then compare the route labels.",
      "Rechne in kleinen Schritten und vergleiche dann die Wegbeschriftungen.",
      "Example: 8 − 3 = 5. Choose the route marked 5; a nearby route can still be wrong.",
      "Beispiel: 8 − 3 = 5. Wähle den Weg mit 5; auch ein naher Weg kann falsch sein."),
  "pathfinder": GameCoaching(
      "8 − 3 = ?",
      5,
      [4, 5, 6],
      "Choose the route with the correct answer.",
      "Wähle den Weg mit der richtigen Antwort.",
      "Read the current expression before choosing a route.",
      "Lies den aktuellen Ausdruck, bevor du einen Weg wählst.",
      "Break the calculation into small steps, then compare the route labels.",
      "Rechne in kleinen Schritten und vergleiche dann die Wegbeschriftungen.",
      "Example: 8 − 3 = 5. Choose the route marked 5; a nearby route can still be wrong.",
      "Beispiel: 8 − 3 = 5. Wähle den Weg mit 5; auch ein naher Weg kann falsch sein."),
  "planet_hopping": GameCoaching(
      "2 × 3 = ?",
      6,
      [5, 6, 8],
      "Which planet matches target 6?",
      "Welcher Planet passt zum Ziel 6?",
      "Read the next landing target.",
      "Lies das nächste Landeziel.",
      "Calculate a planet’s expression before jumping; follow the target sequence.",
      "Berechne den Ausdruck eines Planeten vor dem Sprung und beachte die Zielreihenfolge.",
      "Example: a planet marked 2 × 3 matches target 6. Plan the landing before the jump.",
      "Beispiel: Ein Planet mit 2 × 3 passt zum Ziel 6. Plane die Landung vor dem Sprung."),
  "puzzle_math": GameCoaching(
      "4 + 5 = ?",
      9,
      [8, 9, 10],
      "Find the matching jigsaw slot.",
      "Finde den passenden Puzzlesteckplatz.",
      "Read a piece’s calculation and its slot labels.",
      "Lies die Rechnung auf dem Teil und die Steckplatzbeschriftungen.",
      "Solve the calculation, then rotate the piece until its edges fit.",
      "Löse die Rechnung und drehe das Teil, bis die Kanten passen.",
      "Example: the piece 4 + 5 belongs in slot 9; rotation changes its fit, not its answer.",
      "Beispiel: Das Teil 4 + 5 gehört in Steckplatz 9. Drehen ändert die Form, nicht die Antwort."),
  "block_counter": GameCoaching(
      "2 + 3 + 1 = ?",
      6,
      [5, 6, 7],
      "Count all blocks in three stacks, including hidden ones.",
      "Zähle alle Würfel in drei Stapeln, auch die verdeckten.",
      "Count whole stacks instead of visible faces.",
      "Zähle ganze Stapel statt sichtbarer Flächen.",
      "Work layer by layer, including blocks behind or beneath others.",
      "Zähle Schicht für Schicht, auch hinter und unter anderen Würfeln.",
      "Example: stacks of heights 2, 3 and 1 contain 6 blocks, even if some faces are hidden.",
      "Beispiel: Stapel der Höhen 2, 3 und 1 enthalten 6 Würfel, auch wenn Flächen verdeckt sind."),
  "perspective_puzzle": GameCoaching(
      "2, 1, 3 → ?",
      3,
      [1, 2, 3],
      "Three occupied columns are viewed from the front. How many silhouette columns remain?",
      "Drei besetzte Spalten werden von vorne betrachtet. Wie viele Silhouettenspalten bleiben?",
      "Check the arrow showing the viewing direction.",
      "Prüfe den Pfeil für die Blickrichtung.",
      "Project each line of blocks to its tallest visible height; hidden blocks do not add width.",
      "Projiziere jede Würfelreihe auf ihre höchste sichtbare Höhe. Verdeckte Würfel erhöhen die Breite nicht.",
      "Example: three side-by-side stacks have a three-column silhouette; a stack behind another shares its column.",
      "Beispiel: Drei nebeneinanderstehende Stapel bilden drei Silhouettenspalten. Ein Stapel dahinter teilt seine Spalte."),
  "codebreaker": GameCoaching(
      "A + A = 8; A = ?",
      4,
      [3, 4, 5],
      "Find the repeated symbol’s value.",
      "Finde den Wert des wiederholten Symbols.",
      "Look for a repeated symbol or an equation with one unknown.",
      "Suche ein wiederholtes Symbol oder eine Gleichung mit einer Unbekannten.",
      "Replace known symbols and solve the remaining equation. Reuse each symbol’s value everywhere.",
      "Ersetze bekannte Symbole und löse die übrige Gleichung. Ein Symbol hat überall denselben Wert.",
      "Example: A + A = 8 means 2 × A = 8, so A = 4.",
      "Beispiel: A + A = 8 bedeutet 2 × A = 8, also A = 4."),
  "cryptex_lock_breaker": GameCoaching(
      "A + 2 = 7; A = ?",
      5,
      [4, 5, 6],
      "Set the missing dial value.",
      "Stelle den fehlenden Wert am Drehrad ein.",
      "Look for an equation linking few dials.",
      "Suche eine Gleichung mit wenigen Drehrädern.",
      "Solve a simple equation first, then substitute its dial value into the others.",
      "Löse zuerst eine einfache Gleichung und setze den Drehradwert in die anderen ein.",
      "Example: A + 2 = 7 gives A = 5. Check every equation using A before unlocking.",
      "Beispiel: A + 2 = 7 ergibt A = 5. Prüfe vor dem Öffnen alle Gleichungen mit A."),
  "kenken": GameCoaching(
      "? + 1 = 3",
      2,
      [1, 2, 3],
      "Complete this addition cage.",
      "Vervollständige diesen Plus-Käfig.",
      "Start with a one-cell cage or a small target.",
      "Beginne mit einem Käfig mit nur einem Feld oder einem kleinen Zielwert.",
      "Use the cage operation and exclude values already present in its row or column.",
      "Nutze die Käfigoperation und schließe Werte aus, die schon in Zeile oder Spalte stehen.",
      "Example: a two-cell +3 cage containing 1 needs 2 in its other cell.",
      "Beispiel: Ein Plus-3-Käfig mit zwei Feldern und einer 1 benötigt im anderen Feld eine 2."),
  "nebula_matrix": GameCoaching(
      "1, 2, ? (1–3)",
      3,
      [1, 2, 3],
      "Complete the row without repeating a number.",
      "Vervollständige die Zeile ohne Zahlwiederholung.",
      "Find a row or column missing one value.",
      "Suche eine Zeile oder Spalte mit nur einer Lücke.",
      "Compare the numbers present with the allowed range, then check the crossing column.",
      "Vergleiche die vorhandenen Zahlen mit dem erlaubten Bereich und prüfe die kreuzende Spalte.",
      "Example: in a 1–3 row containing 1 and 2, the missing value is 3.",
      "Beispiel: In einer Zeile mit Zahlen von 1 bis 3, in der 1 und 2 stehen, fehlt 3."),
  "asteroid_field_navigator": GameCoaching(
      "2 − 1 = ?",
      1,
      [0, 1, 2],
      "A clue has two hazards beside it; one is already marked. How many remain?",
      "Neben einem Hinweis liegen zwei Gefahren; eine ist markiert. Wie viele fehlen?",
      "Choose a numbered cell with few unknown neighbours.",
      "Wähle ein Zahlenfeld mit wenigen unbekannten Nachbarn.",
      "Subtract marked hazards from the clue. If all remaining neighbours must be hazards, mark them; if none remain, they are safe.",
      "Ziehe markierte Gefahren vom Hinweis ab. Müssen alle übrigen Nachbarn Gefahren sein, markiere sie. Fehlt keine mehr, sind sie sicher.",
      "Example: clue 2 with one marked hazard and one unknown neighbour forces that neighbour to be a hazard.",
      "Beispiel: Beim Hinweis 2 mit einer markierten Gefahr und nur einem unbekannten Nachbarn muss dieser Nachbar eine Gefahr sein."),
  "hive_station": GameCoaching(
      "2 − 1 = ?",
      1,
      [0, 1, 2],
      "A clue has two hazards beside it; one is already marked. How many remain?",
      "Neben einem Hinweis liegen zwei Gefahren; eine ist markiert. Wie viele fehlen?",
      "Choose a numbered cell with few unknown neighbours.",
      "Wähle ein Zahlenfeld mit wenigen unbekannten Nachbarn.",
      "Subtract marked hazards from the clue. If all remaining neighbours must be hazards, mark them; if none remain, they are safe.",
      "Ziehe markierte Gefahren vom Hinweis ab. Müssen alle übrigen Nachbarn Gefahren sein, markiere sie. Fehlt keine mehr, sind sie sicher.",
      "Example: clue 2 with one marked hazard and one unknown neighbour forces that neighbour to be a hazard.",
      "Beispiel: Beim Hinweis 2 mit einer markierten Gefahr und nur einem unbekannten Nachbarn muss dieser Nachbar eine Gefahr sein."),
  "cargo_bay_arranger": GameCoaching(
      "2 + 3 + ? = 10",
      5,
      [4, 5, 6],
      "Complete a cargo row with target sum 10.",
      "Vervollständige eine Frachtreihe mit Zielsumme 10.",
      "Inspect gaps and numbers in the row before dropping.",
      "Prüfe Lücken und Zahlen der Reihe vor dem Ablegen.",
      "Plan both the piece shape and the row sum; use rotation or hold to avoid sealing a gap.",
      "Plane sowohl die Form als auch die Reihensumme. Nutze Drehen oder Halten, um keine Lücke einzuschließen.",
      "Example: a row containing 2 and 3 needs another 5 to reach target 10. A matching number still needs a fitting shape.",
      "Beispiel: Eine Reihe mit 2 und 3 benötigt noch 5 für das Ziel 10. Auch die Form muss passen."),
  "quantum_molecule_builder": GameCoaching(
      "2 → [ ] [ ] ■; moves = ?",
      1,
      [1, 2, 3],
      "An atom slides until the wall. How many slide actions reach the last empty cell?",
      "Ein Atom gleitet bis zur Wand. Wie viele Gleitbewegungen führen zum letzten freien Feld?",
      "Find a wall or atom that can stop the selected atom.",
      "Suche eine Wand oder ein Atom, das das gewählte Atom stoppen kann.",
      "Plan the stopping square, not just the direction. Use other atoms as temporary stops.",
      "Plane das Stoppfeld, nicht nur die Richtung. Nutze andere Atome als vorübergehende Stopper.",
      "Example: one slide crosses both empty cells and stops beside the wall. Count it as one action.",
      "Beispiel: Eine Gleitbewegung überquert beide freien Felder und endet neben der Wand. Das zählt als eine Aktion."),
  "space_station_gridlock": GameCoaching(
      "[A A] → [ ] [ ] EXIT; blockers = ?",
      0,
      [0, 1, 2],
      "How many blockers remain in this exit row?",
      "Wie viele Blockierer stehen noch in dieser Ausgangszeile?",
      "Inspect the player ship’s route to the exit.",
      "Prüfe den Weg des Spielerschiffs zum Ausgang.",
      "Move the blocking ships along their own axes. Clear room for them before moving the player ship.",
      "Bewege blockierende Schiffe entlang ihrer Achsen. Schaffe ihnen Platz, bevor du das Spielerschiff bewegst.",
      "Example: with no ship between A and the exit, slide A along its row to leave.",
      "Beispiel: Steht kein Schiff zwischen A und dem Ausgang, schiebe A entlang seiner Zeile hinaus."),
  "star_loader_game": GameCoaching(
      "P → □ → ○; pushes = ?",
      1,
      [1, 2, 3],
      "A box is one step from its goal. How many pushes are needed?",
      "Eine Kiste steht einen Schritt vor ihrem Ziel. Wie oft musst du schieben?",
      "Look behind the box you want to push.",
      "Schau hinter die Kiste, die du schieben willst.",
      "The player must reach the opposite side of the box; avoid pushing boxes into non-goal corners.",
      "Die Spielfigur muss die gegenüberliegende Seite der Kiste erreichen. Vermeide Ecken ohne Ziel.",
      "Example: stand behind the box and push it once onto the goal. You cannot pull it back from a corner.",
      "Beispiel: Stelle dich hinter die Kiste und schiebe sie einmal auf das Ziel. Aus einer Ecke kannst du sie nicht zurückziehen."),
  "robot_path_game": GameCoaching(
      "→ → →; forward commands = ?",
      3,
      [2, 3, 4],
      "Program three forward steps.",
      "Programmiere drei Schritte nach vorne.",
      "Trace the route from the robot’s current direction.",
      "Verfolge den Weg aus der aktuellen Blickrichtung des Roboters.",
      "Turning changes direction without moving. Count forward steps and use obstacles to plan special commands.",
      "Drehen ändert die Richtung ohne Bewegung. Zähle Vorwärtsschritte und plane Spezialbefehle an Hindernissen.",
      "Example: to travel three clear cells straight ahead, use three forward commands. A right turn alone moves zero cells.",
      "Beispiel: Für drei freie Felder geradeaus brauchst du drei Vorwärtsbefehle. Rechtsdrehen allein bewegt den Roboter nicht."),
  "grid_filler_game": GameCoaching(
      "2 × 2 = ?",
      4,
      [2, 4, 6],
      "How many board cells does this square piece cover?",
      "Wie viele Brettfelder bedeckt dieses quadratische Teil?",
      "Look for a tight corner or a narrow uncovered gap.",
      "Suche eine enge Ecke oder eine schmale freie Lücke.",
      "Fit pieces without overlap or empty islands. Rotate the shape before committing a drop.",
      "Lege Teile ohne Überlappungen oder eingeschlossene Lücken. Drehe die Form vor dem Ablegen.",
      "Example: a 2 × 2 square covers four cells. It needs two free rows and two free columns.",
      "Beispiel: Ein 2 × 2-Quadrat bedeckt vier Felder. Es benötigt zwei freie Zeilen und zwei freie Spalten."),
  "hull_plating": GameCoaching(
      "2 × 2 = ?",
      4,
      [2, 4, 6],
      "How many board cells does this square piece cover?",
      "Wie viele Brettfelder bedeckt dieses quadratische Teil?",
      "Look for a tight corner or a narrow uncovered gap.",
      "Suche eine enge Ecke oder eine schmale freie Lücke.",
      "Fit pieces without overlap or empty islands. Rotate the shape before committing a drop.",
      "Lege Teile ohne Überlappungen oder eingeschlossene Lücken. Drehe die Form vor dem Ablegen.",
      "Example: a 2 × 2 square covers four cells. It needs two free rows and two free columns.",
      "Beispiel: Ein 2 × 2-Quadrat bedeckt vier Felder. Es benötigt zwei freie Zeilen und zwei freie Spalten."),
  "star_chart_scan": GameCoaching(
      "3 + 2 = ?",
      5,
      [4, 5, 6],
      "Find a true equation in a straight line.",
      "Finde eine richtige Gleichung in einer geraden Linie.",
      "Start at an equals sign and inspect the line around it.",
      "Beginne an einem Gleichheitszeichen und prüfe die Linie darum.",
      "Read all characters in order along one direction; verify the arithmetic before sweeping.",
      "Lies alle Zeichen der Reihe nach in einer Richtung und prüfe die Rechnung vor dem Markieren.",
      "Example: sweep 3, +, 2, =, 5 along one straight line. A bent path is not an equation.",
      "Beispiel: Markiere 3, +, 2, =, 5 auf einer geraden Linie. Ein geknickter Weg zählt nicht."),
  "comm_relay": GameCoaching(
      "B → A; shift = ?",
      1,
      [1, 2, 3],
      "Decode B as A using a Caesar shift.",
      "Entschlüssele B als A mit einer Caesar-Verschiebung.",
      "Use a revealed letter mapping.",
      "Nutze eine aufgedeckte Buchstabenzuordnung.",
      "For Caesar, apply the same backwards shift to every letter. For other ciphers, follow their mapping table.",
      "Verschiebe bei Caesar jeden Buchstaben gleich weit zurück. Nutze bei anderen Chiffren ihre Zuordnungstabelle.",
      "Example: shifting B back by one gives A, and D back by one gives C.",
      "Beispiel: B um eins zurück ergibt A; D um eins zurück ergibt C."),
  "vault_cracker": GameCoaching(
      "A + B = 5; A = 2; B = ?",
      3,
      [2, 3, 4],
      "Use both code clues.",
      "Nutze beide Codehinweise.",
      "Choose a clue that fixes a digit or sharply limits it.",
      "Wähle einen Hinweis, der eine Ziffer festlegt oder stark einschränkt.",
      "Combine all clues before committing a guess; position and value are separate information.",
      "Verbinde alle Hinweise vor einem Versuch. Position und Wert sind unterschiedliche Informationen.",
      "Example: A + B = 5 with A = 2 leaves B = 3. Recheck other clues before guessing.",
      "Beispiel: A + B = 5 mit A = 2 ergibt B = 3. Prüfe vor dem Versuch auch die anderen Hinweise."),
  "signal_triangulation": GameCoaching(
      "1 + 2 + ? = 6",
      3,
      [1, 2, 3],
      "Complete the signal total.",
      "Vervollständige die Signalsumme.",
      "Use feedback from the previous signal guess.",
      "Nutze die Rückmeldung zum letzten Signalversuch.",
      "Separate correct symbols from correct positions. Keep confirmed evidence while testing another position.",
      "Unterscheide richtige Symbole von richtigen Positionen. Behalte bestätigte Hinweise beim Testen einer anderen Position.",
      "Example: a total of 6 with values 1 and 2 needs 3. A correct total does not prove the positions.",
      "Beispiel: Bei Gesamtsumme 6 und Werten 1 und 2 fehlt 3. Die richtige Summe beweist nicht die Positionen."),
  "crew_manifest": GameCoaching(
      "Zara → 1; Kip → 2; Nova → ?",
      3,
      [1, 2, 3],
      "Each crew member gets one different item. Which remains?",
      "Jedes Crewmitglied bekommt einen anderen Gegenstand. Welcher bleibt übrig?",
      "Start with a direct positive or negative clue.",
      "Beginne mit einem direkten Ja- oder Nein-Hinweis.",
      "Mark a confirmed match and exclude its row and column; repeat with remaining possibilities.",
      "Markiere eine sichere Zuordnung und schließe den Rest ihrer Zeile und Spalte aus. Wiederhole das mit den übrigen Möglichkeiten.",
      "Example: if Zara has item 1 and Kip item 2, Nova must have item 3.",
      "Beispiel: Wenn Zara Gegenstand 1 und Kip Gegenstand 2 hat, muss Nova Gegenstand 3 haben."),
  "alien_tribunal": GameCoaching(
      "A: TRUE; B: FALSE; truth-tellers = ?",
      1,
      [0, 1, 2],
      "A tells the truth and B lies. How many truth-tellers are there?",
      "A sagt die Wahrheit und B lügt. Wie viele Wahrheitssager gibt es?",
      "Pick a statement and test its speaker’s possible role.",
      "Wähle eine Aussage und prüfe die mögliche Rolle ihres Sprechers.",
      "A truth-teller’s whole statement must be true; a liar’s whole statement must be false. Check the assignment against every speaker.",
      "Die ganze Aussage eines Wahrheitssagers muss wahr sein, die eines Lügners falsch. Prüfe die Zuordnung bei jedem Sprecher.",
      "Example: if a truth-teller says “B lies”, B must be a liar. If that speaker lies instead, B must tell the truth.",
      "Beispiel: Sagt ein Wahrheitssager „B lügt“, muss B lügen. Lügt der Sprecher, muss B die Wahrheit sagen."),
  "gravity_well": GameCoaching(
      "A + 2 = 7; A = ?",
      5,
      [4, 5, 6],
      "Keep the scale balanced.",
      "Halte die Waage im Gleichgewicht.",
      "Find a scale with only one unknown object.",
      "Suche eine Waage mit nur einem unbekannten Objekt.",
      "Remove equal known weights from both sides, then share the remaining weight among identical unknowns.",
      "Entferne gleiche bekannte Gewichte auf beiden Seiten und verteile den Rest auf gleiche unbekannte Objekte.",
      "Example: A + 2 = 7 gives A = 5; two copies of A weighing 10 also give A = 5.",
      "Beispiel: A + 2 = 7 ergibt A = 5. Auch zwei A mit Gewicht 10 ergeben A = 5."),
  "sector_painter": GameCoaching(
      "A—B—C; A = 1, B = 2, C = ?",
      1,
      [1, 2, 3],
      "Reuse a colour when regions do not touch. Pick the lowest allowed colour.",
      "Nutze eine Farbe erneut, wenn Gebiete sich nicht berühren. Wähle die kleinste erlaubte Farbnummer.",
      "Inspect the neighbours of an uncoloured region.",
      "Prüfe die Nachbarn eines ungefärbten Gebiets.",
      "Exclude colours used by neighbours; non-neighbouring regions may share a colour.",
      "Schließe Farben der Nachbarn aus. Nicht benachbarte Gebiete dürfen dieselbe Farbe haben.",
      "Example: on path A–B–C, colours 1–2–1 are valid because A and C are not neighbours.",
      "Beispiel: Auf dem Weg A–B–C sind Farben 1–2–1 gültig, weil A und C keine Nachbarn sind."),
  "warp_fold": GameCoaching(
      "1 fold × 1 cut → ? holes",
      2,
      [1, 2, 4],
      "One cut is away from the crease. How many holes appear after unfolding?",
      "Ein Schnitt liegt neben der Faltkante. Wie viele Löcher entstehen beim Aufklappen?",
      "Track the crease and each cut’s distance from it.",
      "Beachte die Faltkante und den Abstand jedes Schnitts dazu.",
      "Unfold in reverse order, reflecting every cut across each crease.",
      "Klappe in umgekehrter Reihenfolge auf und spiegle jeden Schnitt an jeder Faltkante.",
      "Example: one cut through two folded layers creates two mirrored holes away from the crease.",
      "Beispiel: Ein Schnitt durch zwei gefaltete Schichten erzeugt abseits der Faltkante zwei gespiegelte Löcher."),
  "cube_scanner": GameCoaching(
      "top = 2; bottom = ?",
      5,
      [3, 4, 5],
      "Opposite faces of a standard die sum to seven.",
      "Gegenüberliegende Seiten eines normalen Würfels ergeben zusammen sieben.",
      "Find the visible face opposite the requested face.",
      "Suche die sichtbare Seite gegenüber der gesuchten Seite.",
      "Opposite die faces sum to seven. For rolls, track the named face one quarter-turn at a time.",
      "Gegenüberliegende Würfelseiten ergeben sieben. Verfolge beim Rollen die benannte Seite Vierteldrehung für Vierteldrehung.",
      "Example: top 2 means bottom 5. After a roll, track where that 2 moves instead of recounting faces.",
      "Beispiel: Oben 2 bedeutet unten 5. Verfolge beim Rollen, wohin die 2 wandert."),
  "circuit_repair": GameCoaching(
      "15:69 → 16:59; swapped positions = ?",
      2,
      [1, 2, 3],
      "How many digit positions must be selected for one swap?",
      "Wie viele Ziffernpositionen wählst du für einen Tausch?",
      "Find the invalid hour, minute or second digits.",
      "Suche die ungültigen Stunden-, Minuten- oder Sekundenziffern.",
      "Select two positions whose swap gives hours 00–23 and minutes/seconds 00–59.",
      "Wähle zwei Positionen, deren Tausch Stunden von 00 bis 23 und Minuten/Sekunden von 00 bis 59 ergibt.",
      "Example: swap the 5 and 6 in 15:69 to get valid time 16:59.",
      "Beispiel: Tausche 5 und 6 in 15:69 und erhalte die gültige Zeit 16:59."),
  "dark_matter_grid": GameCoaching(
      "OFF → toggle → ?",
      1,
      [0, 1, 2],
      "Use 0 for off and 1 for on. What is the toggled state?",
      "Nutze 0 für aus und 1 für an. Welcher Zustand entsteht beim Umschalten?",
      "Inspect which cells a tap changes.",
      "Prüfe, welche Felder ein Tippen verändert.",
      "Each tap toggles the chosen cell and its orthogonal neighbours. Two taps on the same cell cancel.",
      "Jedes Tippen schaltet das Feld und seine waagerechten und senkrechten Nachbarn um. Zweimal auf dasselbe Feld hebt sich auf.",
      "Example: an off cell toggled once is on; toggled twice it is off again. Plan neighbours together.",
      "Beispiel: Ein ausgeschaltetes Feld ist nach einmal Umschalten an und nach zweimal wieder aus. Plane Nachbarn gemeinsam."),
  "ion_chain": GameCoaching(
      "1—?—1; no equal neighbours",
      2,
      [1, 2, 3],
      "With types 1 and 2, which bead fits between two type-1 beads?",
      "Welche Perle passt bei Typen 1 und 2 zwischen zwei Typ-1-Perlen?",
      "Inspect both neighbours of an empty slot.",
      "Prüfe beide Nachbarn einer Lücke.",
      "Respect every pictured rule, including the last-to-first pair around the ring.",
      "Beachte jede Bildregel, auch das letzte und erste Paar im Ring.",
      "Example: when equal neighbours are forbidden, type 2 fits between two type-1 beads. Also check the ring closure.",
      "Beispiel: Sind gleiche Nachbarn verboten, passt Typ 2 zwischen zwei Typ-1-Perlen. Prüfe auch den Ringschluss."),
  "launch_sequence": GameCoaching(
      "2, 1, 3; adjacent swaps = ?",
      1,
      [1, 2, 3],
      "Sort the sequence with the fewest neighbouring swaps.",
      "Sortiere mit möglichst wenigen Tauschen benachbarter Zahlen.",
      "Find neighbouring numbers in the wrong order.",
      "Suche benachbarte Zahlen in falscher Reihenfolge.",
      "Swap an inverted adjacent pair; each such swap removes one inversion.",
      "Tausche ein vertauschtes Nachbarpaar. Jeder solche Tausch entfernt eine Inversion.",
      "Example: swap 2 and 1 once to turn 2, 1, 3 into 1, 2, 3.",
      "Beispiel: Tausche 2 und 1 einmal und mache aus 2, 1, 3 die Reihenfolge 1, 2, 3."),
  "relic_assembly": GameCoaching(
      "edge 3 | edge ?",
      3,
      [1, 2, 3],
      "Match the glyphs on touching tile edges.",
      "Verbinde gleiche Zeichen an berührenden Kachelkanten.",
      "Choose a gap with two or more placed neighbours.",
      "Wähle eine Lücke mit mindestens zwei gelegten Nachbarn.",
      "Rotate a tile and check every touching edge before placing it.",
      "Drehe eine Kachel und prüfe vor dem Legen jede berührende Kante.",
      "Example: a neighbour showing edge 3 needs edge 3 facing it. A match on one side alone is insufficient.",
      "Beispiel: Zur Nachbarkante 3 muss ebenfalls Kante 3 zeigen. Eine passende Seite allein reicht nicht."),
  "xenobiology_lab": GameCoaching(
      "A: 2 eyes, B: 3 eyes; one each = ?",
      5,
      [4, 5, 6],
      "Count the eyes for one specimen of each type.",
      "Zähle die Augen je eines Exemplars beider Typen.",
      "Compare each species’ eyes and legs with the totals.",
      "Vergleiche Augen und Beine jeder Art mit den Gesamtsummen.",
      "Multiply each species count by its features and add. Both eyes and legs must fit the same counts.",
      "Multipliziere die Anzahl jeder Art mit ihren Merkmalen und addiere. Augen und Beine müssen zu denselben Anzahlen passen.",
      "Example: one 2-eyed A and one 3-eyed B give 5 eyes. Verify their legs too before submitting.",
      "Beispiel: Ein zweiäugiges A und ein dreiäugiges B ergeben 5 Augen. Prüfe vor dem Bestätigen auch ihre Beine."),
  "galactic_market": GameCoaching(
      "change 12 − visible 2; 2 hidden coins = ? each",
      5,
      [2, 5, 10],
      "Find the value of each identical hidden coin.",
      "Finde den Wert jeder gleichen verdeckten Münze.",
      "Subtract the visible coins from the required change.",
      "Ziehe sichtbare Münzen vom nötigen Wechselgeld ab.",
      "Divide the remaining amount by the number of hidden coins; then check any denomination clue.",
      "Teile den Restbetrag durch die Zahl verdeckter Münzen und prüfe den Hinweis zum Münzwert.",
      "Example: change 12 minus visible 2 leaves 10. Two identical hidden coins must be worth 5 each.",
      "Beispiel: Wechselgeld 12 minus sichtbare 2 ergibt 10. Zwei gleiche verdeckte Münzen sind je 5 wert."),
  "asteroid_duel": GameCoaching(
      "6 asteroids, take 1–3; leave = ?",
      5,
      [3, 4, 5],
      "Taking the last asteroid loses. Which count should you leave?",
      "Wer den letzten Asteroiden nimmt, verliert. Welche Anzahl solltest du übrig lassen?",
      "Look at the remaining count and maximum legal take.",
      "Prüfe die übrige Anzahl und die höchste erlaubte Entnahme.",
      "When possible, leave one more than a multiple of maximum take plus one.",
      "Lasse möglichst eins mehr als ein Vielfaches von maximaler Entnahme plus eins übrig.",
      "Example: from 6 with a maximum take of 3, take 1 and leave 5. Then answer each opponent take with enough to total 4, leaving them the last asteroid.",
      "Beispiel: Bei 6 und maximal 3 nimmst du 1 und lässt 5. Ergänze danach jede Entnahme des Gegners auf 4, damit ihm der letzte Asteroid bleibt."),
  "chrono_repair": GameCoaching(
      "display 10:30 + error 00:30; true hour = ?",
      10,
      [9, 10, 11],
      "The clock is thirty minutes fast. What hour belongs to the true time?",
      "Die Uhr geht dreißig Minuten vor. Zu welcher Stunde gehört die richtige Zeit?",
      "Read whether the clock is fast, slow, mirrored or has swapped hands.",
      "Lies, ob die Uhr vorgeht, nachgeht, gespiegelt ist oder vertauschte Zeiger hat.",
      "Undo the stated malfunction. For an offset, subtract a fast clock’s error or add a slow clock’s error.",
      "Mache die angegebene Störung rückgängig. Ziehe den Fehler einer vorgehenden Uhr ab oder addiere ihn bei einer nachgehenden.",
      "Example: display 10:30 with +30 minutes error means true time 10:00.",
      "Beispiel: Anzeige 10:30 mit +30 Minuten Fehler bedeutet richtige Zeit 10:00."),
  "void_crossing": GameCoaching(
      "1 guardian + 1 passenger; passenger seats = ?",
      1,
      [1, 2, 3],
      "A shuttle has one passenger seat. How many creatures can you board?",
      "Ein Shuttle hat einen Passagierplatz. Wie viele Wesen kannst du einladen?",
      "Check both stations after a proposed crossing.",
      "Prüfe beide Stationen nach einer geplanten Überfahrt.",
      "Keep conflicting creatures supervised; the shuttle may return empty when necessary.",
      "Lasse unverträgliche Wesen nicht unbeaufsichtigt. Das Shuttle darf bei Bedarf leer zurückkehren.",
      "Example: first carry the creature that conflicts with both others, then return alone so neither bank has an unsafe pair.",
      "Beispiel: Transportiere zuerst das Wesen, das mit beiden anderen unverträglich ist, und kehre allein zurück. So bleibt kein gefährliches Paar zurück."),
  "arithmancer_duel": GameCoaching(
      "2 + 3 = ?",
      5,
      [4, 5, 6],
      "Build an expression from your number and operation cards.",
      "Baue einen Ausdruck aus Zahlen- und Rechenzeichenkarten.",
      "Inspect available number, operation and bracket cards.",
      "Prüfe Zahlen-, Rechenzeichen- und Klammerkarten.",
      "Build a valid expression first, then compare its result with the enemy’s mathematical properties and your energy.",
      "Baue zuerst einen gültigen Ausdruck. Vergleiche dann das Ergebnis mit den mathematischen Eigenschaften des Gegners und deiner Energie.",
      "Example: cards 2, +, 3 produce 5. Before attacking, check whether a result of 5 helps against this opponent.",
      "Beispiel: Karten 2, +, 3 ergeben 5. Prüfe vor dem Angriff, ob das Ergebnis 5 gegen diesen Gegner hilft."),
  "creature_forge": GameCoaching(
      "2 heads × 2 bodies × 2 tails = ?",
      8,
      [4, 6, 8],
      "Count all combinations before exclusions.",
      "Zähle alle Kombinationen vor Ausschlüssen.",
      "Count choices for each body part.",
      "Zähle die Möglichkeiten für jedes Körperteil.",
      "Multiply independent choices, then subtract forbidden combinations.",
      "Multipliziere unabhängige Möglichkeiten und ziehe verbotene Kombinationen ab.",
      "Example: 2 × 2 × 2 gives eight creatures before restrictions.",
      "Beispiel: 2 × 2 × 2 ergibt acht Wesen vor Einschränkungen."),
};

const _germanPracticeBoards = <String, String>{
  '2 → [ ] [ ] ■; moves = ?': '2 → [ ] [ ] ■; Züge = ?',
  '[A A] → [ ] [ ] EXIT; blockers = ?':
      '[A A] → [ ] [ ] AUSGANG; Hindernisse = ?',
  'P → □ → ○; pushes = ?': 'P → □ → ○; Schübe = ?',
  '→ → →; forward commands = ?': '→ → →; Vorwärtsbefehle = ?',
  'B → A; shift = ?': 'B → A; Verschiebung = ?',
  'A: TRUE; B: FALSE; truth-tellers = ?':
      'A: WAHR; B: FALSCH; Wahrheitsredner = ?',
  '1 fold × 1 cut → ? holes': '1 Faltung × 1 Schnitt → ? Löcher',
  'top = 2; bottom = ?': 'oben = 2; unten = ?',
  '15:69 → 16:59; swapped positions = ?':
      '15:69 → 16:59; vertauschte Stellen = ?',
  'OFF → toggle → ?': 'AUS → umschalten → ?',
  '1—?—1; no equal neighbours': '1—?—1; keine gleichen Nachbarn',
  '2, 1, 3; adjacent swaps = ?': '2, 1, 3; Nachbartausch = ?',
  'edge 3 | edge ?': 'Kante 3 | Kante ?',
  'A: 2 eyes, B: 3 eyes; one each = ?': 'A: 2 Augen, B: 3 Augen; je eines = ?',
  'change 12 − visible 2; 2 hidden coins = ? each':
      'Wechselgeld 12 − sichtbar 2; 2 verdeckte Münzen = ? pro Münze',
  '6 asteroids, take 1–3; leave = ?': '6 Asteroiden, nimm 1–3; übrig = ?',
  'display 10:30 + error 00:30; true hour = ?':
      'Anzeige 10:30 + Fehler 00:30; echte Stunde = ?',
  '1 guardian + 1 passenger; passenger seats = ?':
      '1 Wächter + 1 Passagier; Passagierplätze = ?',
  '2 heads × 2 bodies × 2 tails = ?': '2 Köpfe × 2 Körper × 2 Schwänze = ?',
};
