// lib/features/games/services/dock_clearance_logic.dart
//
// Rush Hour / sliding block puzzle generator.
// Ships occupy 1x2 or 1x3 cells, slide along their axis.
// Red ship must reach the exit (right edge).
// Puzzles generated by placing ships then verifying solvability via BFS.

import 'dart:math' as math;
import 'dart:collection';

enum ShipOrientation { horizontal, vertical }

class Ship {
  final int id;
  final int row;
  final int col;
  final int length;
  final ShipOrientation orientation;
  final bool isTarget; // red ship

  Ship({
    required this.id,
    required this.row,
    required this.col,
    required this.length,
    required this.orientation,
    this.isTarget = false,
  });

  Ship copyWith({int? row, int? col}) {
    return Ship(
      id: id,
      row: row ?? this.row,
      col: col ?? this.col,
      length: length,
      orientation: orientation,
      isTarget: isTarget,
    );
  }

  List<List<int>> get cells {
    final result = <List<int>>[];
    for (int i = 0; i < length; i++) {
      if (orientation == ShipOrientation.horizontal) {
        result.add([row, col + i]);
      } else {
        result.add([row + i, col]);
      }
    }
    return result;
  }
}

class DockClearancePuzzle {
  final int boardSize;
  final List<Ship> ships;
  final int exitRow;
  final int optimalMoves;

  DockClearancePuzzle({
    required this.boardSize,
    required this.ships,
    required this.exitRow,
    required this.optimalMoves,
  });

  /// Build a grid representation from ships.
  static List<List<int>> buildGrid(int size, List<Ship> ships) {
    final grid = List.generate(size, (_) => List.filled(size, -1));
    for (final ship in ships) {
      for (final cell in ship.cells) {
        if (cell[0] >= 0 && cell[0] < size && cell[1] >= 0 && cell[1] < size) {
          grid[cell[0]][cell[1]] = ship.id;
        }
      }
    }
    return grid;
  }

  /// Check if target ship can exit (reaches right edge).
  static bool isTargetAtExit(List<Ship> ships, int boardSize) {
    final target = ships.firstWhere((s) => s.isTarget);
    return target.col + target.length == boardSize;
  }

  /// Encode state as string for BFS visited set.
  static String encodeState(List<Ship> ships) {
    final parts = ships.map((s) => '${s.id}:${s.row},${s.col}').toList();
    parts.sort();
    return parts.join('|');
  }

  /// BFS to find optimal solution length.
  static int? solveBFS(int boardSize, List<Ship> ships, {int maxStates = 50000}) {
    final initialState = encodeState(ships);
    if (isTargetAtExit(ships, boardSize)) return 0;

    final visited = <String>{initialState};
    final queue = Queue<_BFSNode>();
    queue.add(_BFSNode(ships: List.from(ships), depth: 0));

    while (queue.isNotEmpty && visited.length < maxStates) {
      final node = queue.removeFirst();

      // Try all possible moves
      for (int i = 0; i < node.ships.length; i++) {
        final ship = node.ships[i];

        // Try sliding in both directions along the ship's axis
        for (final delta in [-1, 1]) {
          Ship? moved;
          if (ship.orientation == ShipOrientation.horizontal) {
            moved = ship.copyWith(col: ship.col + delta);
          } else {
            moved = ship.copyWith(row: ship.row + delta);
          }

          // Check bounds
          bool valid = true;
          for (final cell in moved.cells) {
            if (cell[0] < 0 || cell[0] >= boardSize ||
                cell[1] < 0 || cell[1] >= boardSize) {
              valid = false;
              break;
            }
          }
          if (!valid) continue;

          // Check collision with other ships
          final newShips = List<Ship>.from(node.ships);
          newShips[i] = moved;

          bool collision = false;
          final grid = List.generate(boardSize, (_) => List.filled(boardSize, -1));
          for (final s in newShips) {
            for (final cell in s.cells) {
              if (grid[cell[0]][cell[1]] != -1 && grid[cell[0]][cell[1]] != s.id) {
                collision = true;
                break;
              }
              grid[cell[0]][cell[1]] = s.id;
            }
            if (collision) break;
          }
          if (collision) continue;

          final state = encodeState(newShips);
          if (visited.contains(state)) continue;
          visited.add(state);

          if (isTargetAtExit(newShips, boardSize)) {
            return node.depth + 1;
          }

          queue.add(_BFSNode(ships: newShips, depth: node.depth + 1));
        }
      }
    }

    return null; // No solution found within limit
  }

  /// Generate a puzzle with guaranteed solvability.
  static DockClearancePuzzle generate({
    required int boardSize,
    required int shipCount,
    required int minMoves,
    int? seed,
  }) {
    final rng = math.Random(seed);

    for (int attempt = 0; attempt < 200; attempt++) {
      final ships = <Ship>[];

      // Place target ship (always horizontal, on a random row)
      final targetRow = rng.nextInt(boardSize);
      final targetCol = rng.nextInt(boardSize - 2); // leave room for length 2
      ships.add(Ship(
        id: 0,
        row: targetRow,
        col: targetCol,
        length: 2,
        orientation: ShipOrientation.horizontal,
        isTarget: true,
      ));

      // Place remaining ships
      int placed = 1;
      int tries = 0;
      while (placed < shipCount && tries < 100) {
        tries++;
        final orientation = rng.nextBool()
            ? ShipOrientation.horizontal
            : ShipOrientation.vertical;
        final length = rng.nextBool() ? 2 : 3;

        int maxRow = orientation == ShipOrientation.vertical
            ? boardSize - length
            : boardSize - 1;
        int maxCol = orientation == ShipOrientation.horizontal
            ? boardSize - length
            : boardSize - 1;

        if (maxRow < 0 || maxCol < 0) continue;

        final row = rng.nextInt(maxRow + 1);
        final col = rng.nextInt(maxCol + 1);

        final newShip = Ship(
          id: placed,
          row: row,
          col: col,
          length: length,
          orientation: orientation,
        );

        // Check collision
        final grid = buildGrid(boardSize, ships);
        bool valid = true;
        for (final cell in newShip.cells) {
          if (grid[cell[0]][cell[1]] != -1) {
            valid = false;
            break;
          }
        }
        if (!valid) continue;

        ships.add(newShip);
        placed++;
      }

      if (placed < shipCount) continue;

      // Verify solvability and minimum move requirement
      final solution = solveBFS(boardSize, ships);
      if (solution != null && solution >= minMoves) {
        return DockClearancePuzzle(
          boardSize: boardSize,
          ships: ships,
          exitRow: targetRow,
          optimalMoves: solution,
        );
      }
    }

    // Fallback: simple puzzle
    final targetRow = boardSize ~/ 2;
    return DockClearancePuzzle(
      boardSize: boardSize,
      ships: [
        Ship(id: 0, row: targetRow, col: 0, length: 2,
            orientation: ShipOrientation.horizontal, isTarget: true),
        Ship(id: 1, row: targetRow - 1, col: boardSize - 1, length: 2,
            orientation: ShipOrientation.vertical),
      ],
      exitRow: targetRow,
      optimalMoves: 2,
    );
  }
}

class _BFSNode {
  final List<Ship> ships;
  final int depth;
  _BFSNode({required this.ships, required this.depth});
}
